const createError = require("http-errors"); 
const express = require("express");
const path = require("path"); 
const cookieParser = require("cookie-parser"); 
const session = require("express-session"); 
const debug = require("debug")("personalapp:server");
const layouts = require("express-ejs-layouts");
const axios = require("axios");

const Diary = require("./models/Diary");

const mongoose = require("mongoose");
const mongodb_URI = "mongodb+srv://cbh534:QxddCgG1AxFFDtFe@cluster0.zofxv.mongodb.net/test"

mongoose.connect(mongodb_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});
mongoose.set("useFindAndModify", false);
mongoose.set("useCreateIndex", true);

const db = mongoose.connection;
db.on("error", console.error.bind(console, "connection error:"));
db.once("open", function () {
  console.log("You successfully connect to the diary webapp");
});

const app = express();


app.set("views", path.join(__dirname, "views"));
app.set("view engine", "ejs");

// this allows us to use page layout for the views
// so we don't have to repeat the headers and footers on every page ...
// the layout is in views/layout.ejs
app.use(layouts);

// Here we process the requests so they are easy to handle
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

// Here we specify that static files will be in the public folder
app.use(express.static(path.join(__dirname, "public")));

// Here we enable session handling using cookies
app.use(
  session({
    secret: "zzbbyanana789sdfa8f9ds8f90ds87f8d9s789fds", // this ought to be hidden in process.env.SECRET
    resave: false,
    saveUninitialized: false,
  })
);





// specify that the server should render the views/index.ejs page for the root path
// and the index.ejs code will be wrapped in the views/layouts.ejs code which provides
// the headers and footers for all webpages generated by this app
app.get("/", (req, res, next) => {
  res.render("index");
});

app.get("/about", (req, res, next) => {
  res.render("about");
});

app.get(
  "/diary",
  async (req, res, next) => {
    try {
      let items = await Diary.find(); 
      res.locals.items = items; 
      res.render("diary"); 
    } catch (e) {
      next(e);
    }
  }
);

app.post("/diary/add", async (req, res, next) => {
  try {
    const { title, weather, content } = req.body; 
    const createdAt = new Date(); 
    let data = { title, content, weather, createdAt }; 
    let item = new Diary(data); 
    await item.save(); 
    res.redirect("/diary"); 
  } catch (e) {
    next(e);
  }
});

app.get("/diary/delete/:itemId", async (req, res, next) => {
  try {
    const itemId = req.params.itemId; 
    await Diary.deleteOne({ _id: itemId }); 
    res.redirect("/diary"); 
  } catch (e) {
    next(e);
  }
});

app.get(
  "/diary/show/:itemId",
  async (req, res, next) => {
    const { itemId } = req.params;
    const item = await Diary.findOne({ _id: itemId });
    res.locals.item = item;
    res.render("diarydetail");
  }
);


// here we catch 404 errors and forward to error handler
app.use(function (req, res, next) {
  next(createError(404));
});

// this processes any errors generated by the previous routes
// notice that the function has four parameters which is how Express indicates it is an error handler
app.use(function (err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get("env") === "development" ? err : {};
  // render the error page
  res.status(err.status || 500);
  res.render("error");
});

// *********************************************************** //
//  Starting up the server!
// *********************************************************** //
//Here we set the port to use between 1024 and 65535  (2^16-1)
const port = "5151";
app.set("port", port);

// and now we startup the server listening on that port
const http = require("http");
const server = http.createServer(app);

server.listen(port);

function onListening() {
  var addr = server.address();
  var bind = typeof addr === "string" ? "pipe " + addr : "port " + addr.port;
  debug("Listening on " + bind);
}

function onError(error) {
  if (error.syscall !== "listen") {
    throw error;
  }

  var bind = typeof port === "string" ? "Pipe " + port : "Port " + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case "EACCES":
      console.error(bind + " requires elevated privileges");
      process.exit(1);
      break;
    case "EADDRINUSE":
      console.error(bind + " is already in use");
      process.exit(1);
      break;
    default:
      throw error;
  }
}

server.on("error", onError);

server.on("listening", onListening);

module.exports = app;
